// <auto-generated>
//     Generated by the FSharp WriteCodeFragment class.
// </auto-generated>
namespace FSharp

open System
open System.Reflection


[<assembly: AssemblyTitle("Forest.Web.WebSharper")>]
[<assembly: AssemblyProduct("Forest.Web.WebSharper")>]
[<assembly: AssemblyDescription("A library to integrate WebSharper with Forest.")>]
[<assembly: AssemblyCompany("Virtual Dimensions")>]
[<assembly: AssemblyCopyright("Copyright © Virtual Dimensions 2013-2019")>]
[<assembly: AssemblyTrademark("")>]
[<assembly: AssemblyConfiguration("Debug")>]
[<assembly: AssemblyCulture("")>]
[<assembly: System.Runtime.InteropServices.GuidAttribute("{B3D50628-4D5D-4719-9B3C-11E2B2DAF9B6}")>]
[<assembly: AssemblyVersion("2.0.2263.24141")>]
[<assembly: AssemblyFileVersion("2.0.2263.24141")>]
[<assembly: AssemblyInformationalVersion("2.0.2263.24141")>]
do()
