version: 3.0.1.{build}

pull_requests:
  do_not_increment_build_number: true
skip_branch_with_pr: true
skip_tags: true

image: Visual Studio 2019
platform: Any CPU

artifacts:
  - path: dist/*.nupkg
    name: NuGet Package
  - path: dist/*.snupkg
    name: NuGet Symbols Package
cache:
  - '%USERPROFILE%\.nuget\packages'
  - '%LocalAppData%\NuGet\Cache'
  - '%LocalAppData%\NuGet\v3-cache'

build_script:
  - ps: "git submodule init -q \ngit submodule update -q \ngit submodule -q foreach git fetch origin -q \ngit submodule -q foreach git pull origin master -q"
  - ps: "dotnet build -p:Version=$env:VERSION -p:ContinuousIntegrationBuild=true -c $env:CONFIGURATION \ndotnet pack -p:Version=$env:VERSION -p:ContinuousIntegrationBuild=true -c $env:CONFIGURATION --no-restore"

for:
  - branches:
      only:
        - master
    environment:
      CONFIGURATION: Release
    init:
      - ps: "$env:VERSION=$env:APPVEYOR_BUILD_VERSION"
    cache:
    deploy:
      - provider: NuGet
        api_key:
          secure: +B5+EqlhISIB7cB1WCNaKvtD9k8o5Bz+Cvac3x1QA56B2Qe1bLimqG/a4UxBX4aO
        on:
          branch: master

  - branches:
      only:
        - /alpha|beta|preview|rc|snapshot/
    version: 3.0.1-{branch}-{build}
    environment:
      CONFIGURATION: Release
    init:
      - ps: "$env:VERSION=$env:APPVEYOR_BUILD_VERSION"
    deploy:
      - provider: NuGet
        api_key:
          secure: +B5+EqlhISIB7cB1WCNaKvtD9k8o5Bz+Cvac3x1QA56B2Qe1bLimqG/a4UxBX4aO

  - branches:
      only:
        - pr
    init:
      - ps: "$env:VERSION=\"$env:APPVEYOR_BUILD_VERSION-$env:APPVEYOR_PULL_REQUEST_HEAD_REPO_BRANCH+$env:APPVEYOR_PULL_REQUEST_HEAD_COMMIT\""