// <auto-generated>
//     Generated by the FSharp WriteCodeFragment class.
// </auto-generated>
namespace FSharp

open System
open System.Reflection


[<assembly: AssemblyTitle("Forest.Core")>]
[<assembly: AssemblyProduct("Forest.Core")>]
[<assembly: AssemblyDescription("Forest (Front-end over REST) is a UI abstraction framework for creating fully-functional applications while being agnostic of the presentation layer")>]
[<assembly: AssemblyCompany("Virtual Dimensions")>]
[<assembly: AssemblyCopyright("Copyright © Virtual Dimensions 2013-2018")>]
[<assembly: AssemblyTrademark("")>]
[<assembly: AssemblyConfiguration("Debug")>]
[<assembly: AssemblyCulture("")>]
[<assembly: System.Runtime.InteropServices.GuidAttribute("{7CBDBFBD-F8FD-4C48-AF8E-0D77923DDF42}")>]
[<assembly: AssemblyVersion("2.0.2180.23393")>]
[<assembly: AssemblyFileVersion("2.0.2180.23393")>]
[<assembly: AssemblyInformationalVersion("2.0.2180.23393")>]
do()
